name: ppi-splitting-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.14
  - certifi
  - blast
  - cd-hit
  - kahip
  - multiqc
  - scikit-learn
  - numpy
  - matplotlib
  - plotly
  - pip:
    - torch
    - transformers
    - sentencepiece
    - protobuf
